version: "3.7"

services:
  application:
    container_name: ${_Values_root_name}-application
    image:  ${_Values_image_repository}${_Values_image_native}:${_Values_image_tag}
    restart: 'no'
    ports:
      - "${_Values_service_port}:${_Values_service_port}"
    entrypoint: ${_Values_resources_entrypoint}

    healthcheck:
      test: "curl -f http://localhost:${_Values_service_port}/actuator/health || exit 1"
      disable: ${_Values_health_check_disabled} #disabled for native images because of no curl
      interval: 5s
      timeout: 10s
      retries: 5

    volumes:
      - tmp:/tmp
      - applogs:/usr/share/logs
    networks:
      - ${_Values_root_name}-net
    environment:
      #application
      TZ: Europe/Berlin
      server.port: "${_Values_service_port}"
      server.tomcat.threads.max: "20"
      server.forward-headers-strategy: FRAMEWORK

      #security
      security.authentication.enabled: "false"

      #monitoring
      management.endpoint.health.show-details: always
      management.endpoints.web.exposure.include: "health,heapdump,circuitbreakers,prometheus"

      #tracing
      spring.application.name: "person-service"
      management.tracing.sampling.probability: "1.0"
      logging.level.io.opentelemetry.exporter: "OFF"
      management.otlp.tracing.endpoint: "http://host.docker.internal:4318/v1/traces"

      #persistence
      spring.datasource.url: "jdbc:postgresql://postgres:5432/person"
      spring.datasource.hikari.maximum-pool-size: "10"
      spring.datasource.hikari.connection-timeout: "10000"

      multi-tenancy.tenants: "0,5"
      multi-tenancy.schema-prefix: "core_"
      database.provisioning.goals: "-migrate -import-demo-data"

      #adapter
      adapter.calleeservice.url: "http://host.docker.internal:50900"
      adapter.calleeservice.timeout: "10000"

      #secrets
      spring.datasource.username: "person-service"
      spring.datasource.password: "person-service"

      adapter.calleeservice.user: "YWRtaW4="
      adapter.calleeservice.password: "YWRtaW4="

      #log levels
      logging.level.root: "WARN"
      logging.level.org.goafabric: "INFO"
      logging.level.org.springframework: "INFO"
      logging.level.org.flywaydb.core: "INFO"
      logging.level.org.hibernate.SQL: "INFO"


    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: ${_Values_root_name}-postgres
    image: postgres:16.0
    restart: 'no'
    ports:
      - 50810:5432
    environment:
      TZ: "Europe/Berlin"
      POSTGRES_DB: "person"

      #secrets
      POSTGRES_USER: "person-service"
      POSTGRES_PASSWORD: "person-service"

    command: postgres -c 'shared_buffers=64MB' -c 'max_connections=30' -c 'shared_preload_libraries=pg_stat_statements'

    healthcheck:
      test: "sh -c pg_isready"
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ${_Values_root_name}-net

  nginx:
    container_name: ${_Values_root_name}-nginx
    image: nginx:1.22.1
    restart: 'no'
    ports:
      - 8080:80
#      - 444:443
    networks:
      - ${_Values_root_name}-net
    volumes:
      - ./nginx/nginx${_Values_nginx_oidc}.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/ssl/
    depends_on:
      application:
        condition: service_started

volumes:
    tmp:
    applogs:
    pgdata:

networks:
  person-service-net:
    driver: bridge